---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.console/summary: "[Fabric8 Console](http://fabric8.io/v2/console.html)\
      \ for working with Fabric8 and Kubernetes"
    description: "Creates an instance of the <a href=\"http://fabric8.io/v2/console.html\"\
      >Fabric8 Console</a> for working with fabric8 and kubernetes."
    fabric8.console/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg"
  labels: {}
  name: "console"
data:
  github-oauth-client-id: "${GITHUB_OAUTH_CLIENT_ID}"
  github-oauth-client-secret: "${GITHUB_OAUTH_CLIENT_SECRET}"
  auth-mode: "basic"
  master-uri: "k8s"
